### ISSUE TITLE
check species names

### ISSUE THREAD

**Issue by bowlerbear** [CecSve/InsectMobile_Diversity_and_Biomass#15]
Bottom section of script 01 checks the names of the species.

Mostly accepted (95%), we have 240 synonyms and 4 doubtful status

The function at the bottom gets the accepted name of these species according to GBIF.

Just guide me on what I can do next.
e.g., check genus too?
replace the species names with their accepted names in taxonomy_cleaned_sub ?

**Comment by CecSve** [comment]
We should not use GBIFs backbone to reassign names since it is not the most updated version - I just wanted to have (all) the synonyms in the data so we can check if the species is already registered for DK (if we have time). I used CoL checklist to assign names so that should be the most updated accepted names we have already. 

So don't change the accepted names in taxonomy_cleaned_sub and don't bother with genus. I will

- [ ] make sure Janzen names are removed from species and genus before the synonym check is carried out

**Comment by CecSve** [comment]
99.9% accepted now, but 241 synonyms and 4 doubtfull. 

- [ ] add the accepted names to the taxonomy file instead of synonyms (keep synonyms and other relevant taxonomy data)

**Comment by CecSve** [comment]
I have decided not to add the accepted names to the taxonomy for now, but have saved a list of the synonyms (+ doubtful) if we need to use the species level data at some point.

The new taxonomy file is called 'taxonomy_cleaned'.
